# Generated by Django 2.2.3 on 2020-08-01 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_image', models.ImageField(upload_to='images/')),
                ('project_title', models.CharField(max_length=20)),
                ('proejct_summary', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
