# Generated by Django 3.0.8 on 2020-08-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20200802_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_tech',
        ),
        migrations.AddField(
            model_name='project',
            name='project_tech',
            field=models.ManyToManyField(default=None, to='jobs.Technology'),
        ),
    ]
